import typing

from BaseClasses import Item, ItemClassification
from .Names import ItemName

# Our Base ID, we will reserve this and the next 200 id's for our items
baseID = 25000

class ItemData(typing.NamedTuple):
    code: typing.Optional[int]
    classification: ItemClassification
    value: int = 0

class Pikmin2Item(Item):
    game: str = "Pikmin 2"

    def __init__(self, name, classification: ItemClassification, code: int = None, player: int = None):
        super(Pikmin2Item, self).__init__(name, classification, code, player)

treasures = {
    ItemName.cupids_grenade: ItemData(baseID, ItemClassification.progression, 20),
    ItemName.sunseed_berry: ItemData(baseID+1, ItemClassification.progression, 170),
    ItemName.combustion_berry: ItemData(baseID+2, ItemClassification.progression, 190),
    ItemName.seed_of_greed: ItemData(baseID+3, ItemClassification.progression, 70),
    ItemName.disguised_delicacy: ItemData(baseID+4, ItemClassification.progression, 40),
    ItemName.insect_condo: ItemData(baseID+5, ItemClassification.progression, 40),
    ItemName.citrus_lump: ItemData(baseID+6, ItemClassification.progression, 180),
    ItemName.spiny_alien_treat: ItemData(baseID+7, ItemClassification.progression, 50),
    ItemName.anxious_sprout: ItemData(baseID+8, ItemClassification.progression, 50),
    ItemName.child_of_the_earth: ItemData(baseID+9, ItemClassification.progression, 40),
    ItemName.love_nugget: ItemData(baseID+10, ItemClassification.progression, 40),
    ItemName.infernal_vegetable: ItemData(baseID+11, ItemClassification.progression, 30),
    ItemName.antihiccup_fungus: ItemData(baseID+12, ItemClassification.progression, 30),
    ItemName.toxic_toadstool: ItemData(baseID+13, ItemClassification.progression, 30),
    ItemName.growshroom: ItemData(baseID+14, ItemClassification.progression, 50),
    ItemName.onion_replica: ItemData(baseID+15, ItemClassification.progression, 30),
    ItemName.science_project: ItemData(baseID+16, ItemClassification.progression, 20),
    ItemName.pilgrim_bulb: ItemData(baseID+17, ItemClassification.progression, 55),
    ItemName.arboreal_frippery: ItemData(baseID+18, ItemClassification.progression, 10),
    ItemName.conifer_spire: ItemData(baseID+19, ItemClassification.progression, 15),
    ItemName.armored_nut: ItemData(baseID+20, ItemClassification.progression, 60),
    ItemName.corpulent_nut: ItemData(baseID+21, ItemClassification.progression, 80),
    ItemName.meat_of_champions: ItemData(baseID+22, ItemClassification.progression, 35),
    ItemName.hideous_victual: ItemData(baseID+23, ItemClassification.progression, 100),
    ItemName.meat_satchel: ItemData(baseID+24, ItemClassification.progression, 40),
    ItemName.taste_sensation: ItemData(baseID+25, ItemClassification.progression, 40),
    ItemName.triple_sugar_threat: ItemData(baseID+26, ItemClassification.progression, 60),
    ItemName.compelling_cookie: ItemData(baseID+27, ItemClassification.progression, 10),
    ItemName.impenetrable_cookie: ItemData(baseID+28, ItemClassification.progression, 25),
    ItemName.bug_bait: ItemData(baseID+29, ItemClassification.progression, 15),
    ItemName.imperative_cookie: ItemData(baseID+30, ItemClassification.progression, 25),
    ItemName.comfort_cookie: ItemData(baseID+31, ItemClassification.progression, 10),
    ItemName.succulent_mattress: ItemData(baseID+32, ItemClassification.progression, 50),
    ItemName.king_of_sweets: ItemData(baseID+33, ItemClassification.progression, 15),
    ItemName.enamel_buster: ItemData(baseID+34, ItemClassification.progression, 60),
    ItemName.diet_doomer: ItemData(baseID+35, ItemClassification.progression, 25),
    ItemName.pale_passion: ItemData(baseID+36, ItemClassification.progression, 25),
    ItemName.white_goodness: ItemData(baseID+37, ItemClassification.progression, 60),
    ItemName.chocolate_cushion: ItemData(baseID+38, ItemClassification.progression, 40),
    ItemName.sweet_dreamer: ItemData(baseID+39, ItemClassification.progression, 40),
    ItemName.confection_hoop: ItemData(baseID+40, ItemClassification.progression, 60),
    ItemName.pastry_wheel: ItemData(baseID+41, ItemClassification.progression, 35),
    ItemName.possessed_squash: ItemData(baseID+42, ItemClassification.progression, 180),
    ItemName.fossilized_ursidae: ItemData(baseID+43, ItemClassification.progression, 160),
    ItemName.colossal_fossil: ItemData(baseID+44, ItemClassification.progression, 140),
    ItemName.leviathan_feather: ItemData(baseID+45, ItemClassification.progression, 10),
    ItemName.olimarnite_shell: ItemData(baseID+46, ItemClassification.progression, 40),
    ItemName.fortified_delicacy: ItemData(baseID+47, ItemClassification.progression, 60),
    ItemName.scrumptious_shell: ItemData(baseID+48, ItemClassification.progression, 60),
    ItemName.memorial_shell: ItemData(baseID+49, ItemClassification.progression, 100),
    ItemName.mysterious_remains: ItemData(baseID+50, ItemClassification.progression, 150),
    ItemName.crystal_king: ItemData(baseID+51, ItemClassification.progression, 110),
    ItemName.future_orb: ItemData(baseID+52, ItemClassification.progression, 200),
    ItemName.gyroid_bust: ItemData(baseID+53, ItemClassification.progression, 250),
    ItemName.unknown_merit: ItemData(baseID+54, ItemClassification.progression, 100),
    ItemName.lustrous_element: ItemData(baseID+55, ItemClassification.progression, 1000),
    ItemName.mirrored_element: ItemData(baseID+56, ItemClassification.progression, 300),
    ItemName.vorpal_platter: ItemData(baseID+57, ItemClassification.progression, 60),
    ItemName.invigorator: ItemData(baseID+58, ItemClassification.progression, 130),
    ItemName.milk_tub: ItemData(baseID+59, ItemClassification.progression, 60),
    ItemName.merciless_extractor: ItemData(baseID+60, ItemClassification.progression, 90),
    ItemName.broken_food_master: ItemData(baseID+61, ItemClassification.progression, 90),
    ItemName.utter_scrap: ItemData(baseID+62, ItemClassification.progression, 170),
    ItemName.decorative_goo: ItemData(baseID+63, ItemClassification.progression, 80),
    ItemName.masters_instrument: ItemData(baseID+64, ItemClassification.progression, 30),
    ItemName.manual_honer: ItemData(baseID+65, ItemClassification.progression, 130),
    ItemName.implement_of_toil: ItemData(baseID+66, ItemClassification.progression, 55),
    ItemName.heavyduty_magnetizer: ItemData(baseID+67, ItemClassification.progression, 150),
    ItemName.harmonic_synthesizer: ItemData(baseID+68, ItemClassification.progression, 120),
    ItemName.emperor_whistle: ItemData(baseID+69, ItemClassification.progression, 75),
    ItemName.director_of_destiny: ItemData(baseID+70, ItemClassification.progression, 100),
    ItemName.sud_generator: ItemData(baseID+71, ItemClassification.progression, 60),
    ItemName.flame_of_tomorrow: ItemData(baseID+72, ItemClassification.progression, 10),
    ItemName.impediment_scourge: ItemData(baseID+73, ItemClassification.progression, 50),
    ItemName.dimensional_slicer: ItemData(baseID+74, ItemClassification.progression, 100),
    ItemName.time_capsule: ItemData(baseID+75, ItemClassification.progression, 70),
    ItemName.lip_service: ItemData(baseID+76, ItemClassification.progression, 50),
    ItemName.mirrored_stage: ItemData(baseID+77, ItemClassification.progression, 140),
    ItemName.behemoth_jaw: ItemData(baseID+78, ItemClassification.progression, 100),
    ItemName.joy_receptacle: ItemData(baseID+79, ItemClassification.progression, 60),
    ItemName.fleeing_art_form: ItemData(baseID+80, ItemClassification.progression, 75),
    ItemName.danger_chime: ItemData(baseID+81, ItemClassification.progression, 120),
    ItemName.spouse_alert: ItemData(baseID+82, ItemClassification.progression, 120),
    ItemName.innocence_lost: ItemData(baseID+83, ItemClassification.progression, 100),
    ItemName.essential_furnishing: ItemData(baseID+84, ItemClassification.progression, 100),
    ItemName.icon_of_progress: ItemData(baseID+85, ItemClassification.progression, 85),
    ItemName.temporal_mechanism: ItemData(baseID+86, ItemClassification.progression, 110),
    ItemName.mystical_disc: ItemData(baseID+87, ItemClassification.progression, 75),
    ItemName.vacuum_processor: ItemData(baseID+88, ItemClassification.progression, 100),
    ItemName.indomitable_cpu: ItemData(baseID+89, ItemClassification.progression, 100),
    ItemName.network_mainbrain: ItemData(baseID+90, ItemClassification.progression, 100),
    ItemName.space_wave_receiver: ItemData(baseID+91, ItemClassification.progression, 80),
    ItemName.sulking_antenna: ItemData(baseID+92, ItemClassification.progression, 150),
    ItemName.nouveau_table: ItemData(baseID+93, ItemClassification.progression, 100),
    ItemName.omega_flywheel: ItemData(baseID+94, ItemClassification.progression, 60),
    ItemName.spirit_flogger: ItemData(baseID+95, ItemClassification.progression, 70),
    ItemName.superstrong_stabilizer: ItemData(baseID+96, ItemClassification.progression, 60),
    ItemName.repair_juggernaut: ItemData(baseID+97, ItemClassification.progression, 85),
    ItemName.adamantine_girdle: ItemData(baseID+98, ItemClassification.progression, 70),
    ItemName.massage_girdle: ItemData(baseID+99, ItemClassification.progression, 100),
    ItemName.superstick_textile: ItemData(baseID+100, ItemClassification.progression, 80),
    ItemName.exhausted_superstick: ItemData(baseID+101, ItemClassification.progression, 50),
    ItemName.furious_adhesive: ItemData(baseID+102, ItemClassification.progression, 60),
    ItemName.petrified_heart: ItemData(baseID+103, ItemClassification.progression, 100),
    ItemName.eternal_emerald_eye: ItemData(baseID+104, ItemClassification.progression, 150),
    ItemName.regal_diamond: ItemData(baseID+105, ItemClassification.progression, 100),
    ItemName.tear_stone: ItemData(baseID+106, ItemClassification.progression, 150),
    ItemName.princess_pearl: ItemData(baseID+107, ItemClassification.progression, 100),
    ItemName.crystal_clover: ItemData(baseID+108, ItemClassification.progression, 150),
    ItemName.unspeakable_wonder: ItemData(baseID+109, ItemClassification.progression, 120),
    ItemName.essence_of_rage: ItemData(baseID+110, ItemClassification.progression, 70),
    ItemName.essence_of_despair: ItemData(baseID+111, ItemClassification.progression, 80),
    ItemName.essence_of_true_love: ItemData(baseID+112, ItemClassification.progression, 60),
    ItemName.essence_of_desire: ItemData(baseID+113, ItemClassification.progression, 90),
    ItemName.pink_menace: ItemData(baseID+114, ItemClassification.progression, 100),
    ItemName.joyless_jewel: ItemData(baseID+115, ItemClassification.progression, 100),
    ItemName.frosty_bauble: ItemData(baseID+116, ItemClassification.progression, 100),
    ItemName.gemstar_wife: ItemData(baseID+117, ItemClassification.progression, 100),
    ItemName.gemstar_husband: ItemData(baseID+118, ItemClassification.progression, 100),
    ItemName.universal_com: ItemData(baseID+119, ItemClassification.progression, 100),
    ItemName.omniscient_sphere: ItemData(baseID+120, ItemClassification.progression, 85),
    ItemName.crystallized_telepathy: ItemData(baseID+121, ItemClassification.progression, 120),
    ItemName.love_sphere: ItemData(baseID+122, ItemClassification.progression, 85),
    ItemName.crystallized_telekinesis: ItemData(baseID+123, ItemClassification.progression, 120),
    ItemName.mirth_sphere: ItemData(baseID+124, ItemClassification.progression, 85),
    ItemName.crystallized_clairvoyance: ItemData(baseID+125, ItemClassification.progression, 120),
    ItemName.maternal_sculpture: ItemData(baseID+126, ItemClassification.progression, 55),
    ItemName.extreme_perspirator: ItemData(baseID+127, ItemClassification.progression, 150),
    ItemName.rubber_ugly: ItemData(baseID+128, ItemClassification.progression, 90),
    ItemName.paradoxical_enigma: ItemData(baseID+129, ItemClassification.progression, 80),
    ItemName.silencer: ItemData(baseID+130, ItemClassification.progression, 670),
    ItemName.wiggle_noggin: ItemData(baseID+131, ItemClassification.progression, 85),
    ItemName.coiled_launcher: ItemData(baseID+132, ItemClassification.progression, 70),
    ItemName.boom_cone: ItemData(baseID+133, ItemClassification.progression, 100),
    ItemName.flame_tiller: ItemData(baseID+134, ItemClassification.progression, 120),
    ItemName.doomsday_apparatus: ItemData(baseID+135, ItemClassification.progression, 3000),
    ItemName.aquatic_mine: ItemData(baseID+136, ItemClassification.progression, 80),
    ItemName.magnifying_lens: ItemData(baseID+137, ItemClassification.progression, 120),
    ItemName.air_brake: ItemData(baseID+138, ItemClassification.progression, 100),
    ItemName.worthless_statue: ItemData(baseID+139, ItemClassification.progression, 80),
    ItemName.priceless_statue: ItemData(baseID+140, ItemClassification.progression, 80),
    ItemName.boss_stone: ItemData(baseID+141, ItemClassification.progression, 110),
    ItemName.luck_wafer: ItemData(baseID+142, ItemClassification.progression, 140),
    ItemName.talisman_of_life: ItemData(baseID+143, ItemClassification.progression, 90),
    ItemName.strife_monolith: ItemData(baseID+144, ItemClassification.progression, 150),
    ItemName.chance_totem: ItemData(baseID+145, ItemClassification.progression, 100),
    ItemName.dream_architect: ItemData(baseID+146, ItemClassification.progression, 280),
    ItemName.stone_of_glory: ItemData(baseID+147, ItemClassification.progression, 100),
    ItemName.glee_spinner: ItemData(baseID+148, ItemClassification.progression, 140),
    ItemName.cosmic_archive: ItemData(baseID+149, ItemClassification.progression, 230),
    ItemName.remembered_old_buddy: ItemData(baseID+150, ItemClassification.progression, 250),
    ItemName.fond_gyro_disk: ItemData(baseID+151, ItemClassification.progression, 80),
    ItemName.memorable_gyro_disk: ItemData(baseID+152, ItemClassification.progression, 80),
    ItemName.lost_gyro_disk: ItemData(baseID+153, ItemClassification.progression, 80),
    ItemName.favorite_gyro_disk: ItemData(baseID+154, ItemClassification.progression, 80),
    ItemName.treasured_gyro_disk: ItemData(baseID+155, ItemClassification.progression, 80),
    ItemName.proton_aa: ItemData(baseID+156, ItemClassification.progression, 90),
    ItemName.durable_energy_cell: ItemData(baseID+157, ItemClassification.progression, 160),
    ItemName.courage_reactor: ItemData(baseID+158, ItemClassification.progression, 280),
    ItemName.fuel_reservoir: ItemData(baseID+159, ItemClassification.progression, 120),
    ItemName.drone_supplies: ItemData(baseID+160, ItemClassification.progression, 130),
    ItemName.patience_tester: ItemData(baseID+161, ItemClassification.progression, 130),
    ItemName.endless_repository: ItemData(baseID+162, ItemClassification.progression, 130),
    ItemName.fruit_guard: ItemData(baseID+163, ItemClassification.progression, 130),
    ItemName.nutrient_silo: ItemData(baseID+164, ItemClassification.progression, 130),
    ItemName.stringent_container: ItemData(baseID+165, ItemClassification.progression, 130),
    ItemName.survival_ointment: ItemData(baseID+166, ItemClassification.progression, 90),
    ItemName.healing_cask: ItemData(baseID+167, ItemClassification.progression, 60),
    ItemName.abstract_masterpiece: ItemData(baseID+168, ItemClassification.progression, 30),
    ItemName.optical_illustration: ItemData(baseID+169, ItemClassification.progression, 140),
    ItemName.thirst_activator: ItemData(baseID+170, ItemClassification.progression, 300),
    ItemName.yellow_taste_tyrant: ItemData(baseID+171, ItemClassification.progression, 100),
    ItemName.salivatrix: ItemData(baseID+172, ItemClassification.progression, 30),
    ItemName.gherkin_gate: ItemData(baseID+173, ItemClassification.progression, 100),
    ItemName.alien_billboard: ItemData(baseID+174, ItemClassification.progression, 80),
    ItemName.activity_arouser: ItemData(baseID+175, ItemClassification.progression, 100),
    ItemName.hypnotic_platter: ItemData(baseID+176, ItemClassification.progression, 100),
    ItemName.massive_lid: ItemData(baseID+177, ItemClassification.progression, 100),
    ItemName.pondering_emblem: ItemData(baseID+178, ItemClassification.progression, 100),
    ItemName.happiness_emblem: ItemData(baseID+179, ItemClassification.progression, 100),
    ItemName.quenching_emblem: ItemData(baseID+180, ItemClassification.progression, 100),
    ItemName.drought_ender: ItemData(baseID+181, ItemClassification.progression, 100),
    ItemName.creative_inspiration: ItemData(baseID+182, ItemClassification.progression, 100),
}

explorers_kit = {
    ItemName.spherical_atlas: ItemData(baseID+183, ItemClassification.progression, 200),
    ItemName.geographical_projection: ItemData(baseID+184, ItemClassification.progression, 200),
    ItemName.prototype_detector: ItemData(baseID+185, ItemClassification.progression, 200),
    ItemName.fiveman_napsack: ItemData(baseID+186, ItemClassification.progression, 100),
    ItemName.brute_knuckles: ItemData(baseID+187, ItemClassification.progression, 100),
    ItemName.repugnant_appendage: ItemData(baseID+188, ItemClassification.progression, 100),
    ItemName.stellar_orb: ItemData(baseID+189, ItemClassification.progression, 100),
    ItemName.forged_courage: ItemData(baseID+190, ItemClassification.progression, 100),
    ItemName.dream_material: ItemData(baseID+191, ItemClassification.progression, 100),
    ItemName.justice_alloy: ItemData(baseID+192, ItemClassification.progression, 100),
    ItemName.amplified_amplifier: ItemData(baseID+193, ItemClassification.progression, 100),
    ItemName.professional_noisemaker: ItemData(baseID+194, ItemClassification.progression, 100),
    ItemName.the_key: ItemData(baseID+195, ItemClassification.progression, 100), # Challenge Mode isnt relevant to us, this will be the Wistful Wild unlock
}

# These treasures are weird to randomize since they are also weapons used
# by the titan dweevil boss(king of bugs is not a weapon thats just Louie)
titan_dweevil = {
    ItemName.shock_therapist: ItemData(baseID+196, ItemClassification.progression, 1000),
    ItemName.flare_cannon: ItemData(baseID+197, ItemClassification.progression, 1000),
    ItemName.comedy_bomb: ItemData(baseID+198, ItemClassification.progression, 1000),
    ItemName.monster_pump: ItemData(baseID+199, ItemClassification.progression, 1000),
    ItemName.king_of_bugs: ItemData(baseID+200, ItemClassification.progression, 10),
}

onions = {
    ItemName.onion_red: ItemData(baseID+201, ItemClassification.progression | ItemClassification.useful),
    ItemName.onion_yellow: ItemData(baseID+202, ItemClassification.progression),
    ItemName.onion_blue: ItemData(baseID+203, ItemClassification.progression),
    ItemName.onion_purple: ItemData(baseID+204, ItemClassification.progression),
    ItemName.onion_white: ItemData(baseID+205, ItemClassification.progression),
}

misc = {
    ItemName.victory: ItemData(baseID+206, ItemClassification.progression),
}

item_table = {
    **treasures,
    **explorers_kit,
    **titan_dweevil,
    **onions,
    #**misc,
}

item_groups: typing.Dict[str, str] = {
    "Treasures": [name for name, data in treasures.items()],
    "Explorer's Kit": [name for name, data in explorers_kit.items()],
    "Titan Dweevil": [name for name, data in titan_dweevil.items()],
    "Onions": [name for name, data in onions.items()],
    #"Victory": [name for name, data in misc.items()]
    }