from typing import List, Optional, Tuple, Callable, NamedTuple
from BaseClasses import Location, MultiWorld
from .Names import LocationName, ItemName

# Our Base ID, we will reserve this and the following 200 ids for our locations
baseID = 25000

class Pikmin2Location(Location):
    game: str = "Pikmin 2"

    def __init__(self, player: int, name = "", code = None, parent = None):
        super(Pikmin2Location, self).__init__(player, name, code, parent)
        self.event = code is None

class LocationData(NamedTuple):
    parent_region: str
    name: str
    code: Optional[int]
    rule: Callable = lambda state: True

def get_locations(multiworld: Optional[MultiWorld], player: Optional[int]) -> Tuple[LocationData, ...]:
    location_table: List[LocationData] = {
        # Valley of Repose
        LocationData(LocationName.vor_region1, LocationName.vor_tre1, baseID),
        LocationData(LocationName.vor_region1, LocationName.vor_tre1, baseID),
        LocationData(LocationName.vor_region1, LocationName.vor_tre2, baseID+1),
        LocationData(LocationName.vor_region1, LocationName.vor_tre3, baseID+2, rule=lambda state: state.has(ItemName.onion_white, player)),
        LocationData(LocationName.vor_region1, LocationName.vor_tre4, baseID+3, rule=lambda state: state.has(ItemName.onion_white, player) and state.has(ItemName.onion_blue, player)),
        LocationData(LocationName.vor_region2, LocationName.vor_tre5, baseID+4),
        LocationData(LocationName.vor_region2, LocationName.vor_tre6, baseID+5, rule=lambda state: state.has(ItemName.onion_blue)),
        LocationData(LocationName.vor_region2, LocationName.vor_tre7, baseID+6),
        # Emergence Cave
        LocationData(LocationName.ec_region, LocationName.ec_sub1_tre1, baseID+7),
        LocationData(LocationName.ec_region, LocationName.ec_sub1_tre2, baseID+8),
        LocationData(LocationName.ec_region, LocationName.ec_sub2_tre1, baseID+9),
        # Subterranean Complex
        LocationData(LocationName.scx_region, LocationName.scx_sub1_tre1, baseID+10),
        LocationData(LocationName.scx_region, LocationName.scx_sub1_tre2, baseID+11),
        LocationData(LocationName.scx_region, LocationName.scx_sub2_tre1, baseID+12),
        LocationData(LocationName.scx_region, LocationName.scx_sub2_tre2, baseID+13),
        LocationData(LocationName.scx_region, LocationName.scx_sub3_tre1, baseID+14),
        LocationData(LocationName.scx_region, LocationName.scx_sub3_tre2, baseID+15),
        LocationData(LocationName.scx_region, LocationName.scx_sub3_tre3, baseID+16),
        LocationData(LocationName.scx_region, LocationName.scx_sub5_tre1, baseID+17),
        LocationData(LocationName.scx_region, LocationName.scx_sub5_tre2, baseID+18),
        LocationData(LocationName.scx_region, LocationName.scx_sub6_tre1, baseID+19),
        LocationData(LocationName.scx_region, LocationName.scx_sub6_tre2, baseID+20),
        LocationData(LocationName.scx_region, LocationName.scx_sub6_tre3, baseID+21),
        LocationData(LocationName.scx_region, LocationName.scx_sub7_tre1, baseID+22),
        LocationData(LocationName.scx_region, LocationName.scx_sub7_tre2, baseID+23),
        LocationData(LocationName.scx_region, LocationName.scx_sub7_tre3, baseID+24),
        LocationData(LocationName.scx_region, LocationName.scx_sub9_tre1, baseID+25),
        # Frontier Cavern
        LocationData(LocationName.fc_region, LocationName.fc_sub1_tre1, baseID+26),
        LocationData(LocationName.fc_region, LocationName.fc_sub1_tre2, baseID+27),
        LocationData(LocationName.fc_region, LocationName.fc_sub2_tre1, baseID+28),
        LocationData(LocationName.fc_region, LocationName.fc_sub2_tre2, baseID+29),
        LocationData(LocationName.fc_region, LocationName.fc_sub3_tre1, baseID+30),
        LocationData(LocationName.fc_region, LocationName.fc_sub3_tre2, baseID+31),
        LocationData(LocationName.fc_region, LocationName.fc_sub3_tre3, baseID+32),
        LocationData(LocationName.fc_region, LocationName.fc_sub4_tre1, baseID+33),
        LocationData(LocationName.fc_region, LocationName.fc_sub4_tre2, baseID+34),
        LocationData(LocationName.fc_region, LocationName.fc_sub5_tre1, baseID+35),
        LocationData(LocationName.fc_region, LocationName.fc_sub6_tre1, baseID+36),
        LocationData(LocationName.fc_region, LocationName.fc_sub6_tre2, baseID+37),
        LocationData(LocationName.fc_region, LocationName.fc_sub7_tre1, baseID+38),
        LocationData(LocationName.fc_region, LocationName.fc_sub7_tre2, baseID+39),
        LocationData(LocationName.fc_region, LocationName.fc_sub8_tre1, baseID+40),
        # Awakening Wood
        LocationData(LocationName.aw_region1, LocationName.aw_tre1, baseID+41),
        LocationData(LocationName.aw_region1, LocationName.aw_tre2, baseID+42, rule= lambda state: state.has(ItemName.onion_white, player)),
        LocationData(LocationName.aw_region1, LocationName.aw_tre3, baseID+43, rule= lambda state: state.has(ItemName.onion_yellow, player)),
        LocationData(LocationName.aw_region3, LocationName.aw_tre4, baseID+44),
        LocationData(LocationName.aw_region4, LocationName.aw_tre5, baseID+45),
        LocationData(LocationName.aw_region5, LocationName.aw_tre6, baseID+46),
        LocationData(LocationName.aw_region6, LocationName.aw_tre7, baseID+47),
        # Hole of Beasts
        LocationData(LocationName.hob_region, LocationName.hob_sub1_tre1, baseID+48),
        LocationData(LocationName.hob_region, LocationName.hob_sub3_tre1, baseID+49),
        LocationData(LocationName.hob_region, LocationName.hob_sub3_tre2, baseID+50),
        LocationData(LocationName.hob_region, LocationName.hob_sub4_tre1, baseID+51),
        LocationData(LocationName.hob_region, LocationName.hob_sub4_tre2, baseID+52),
        LocationData(LocationName.hob_region, LocationName.hob_sub5_tre1, baseID+53),
        # White Flower Garden
        LocationData(LocationName.wfg_region, LocationName.wfg_sub1_tre1, baseID+54),
        LocationData(LocationName.wfg_region, LocationName.wfg_sub2_tre1, baseID+55),
        LocationData(LocationName.wfg_region, LocationName.wfg_sub2_tre2, baseID+56),
        LocationData(LocationName.wfg_region, LocationName.wfg_sub3_tre1, baseID+57),
        LocationData(LocationName.wfg_region, LocationName.wfg_sub4_tre1, baseID+58),
        LocationData(LocationName.wfg_region, LocationName.wfg_sub4_tre2, baseID+59),
        LocationData(LocationName.wfg_region, LocationName.wfg_sub5_tre1, baseID+60),
        # Bulblax Kingdom
        LocationData(LocationName.bk_region, LocationName.bk_sub1_tre1, baseID+61),
        LocationData(LocationName.bk_region, LocationName.bk_sub2_tre1, baseID+62),
        LocationData(LocationName.bk_region, LocationName.bk_sub3_tre1, baseID+63),
        LocationData(LocationName.bk_region, LocationName.bk_sub4_tre1, baseID+64),
        LocationData(LocationName.bk_region, LocationName.bk_sub4_tre2, baseID+65),
        LocationData(LocationName.bk_region, LocationName.bk_sub5_tre1, baseID+66),
        LocationData(LocationName.bk_region, LocationName.bk_sub6_tre1, baseID+67),
        LocationData(LocationName.bk_region, LocationName.bk_sub6_tre2, baseID+68),
        LocationData(LocationName.bk_region, LocationName.bk_sub7_tre1, baseID+69),
        LocationData(LocationName.bk_region, LocationName.bk_sub7_tre2, baseID+70),
        # Snagret Hole
        LocationData(LocationName.sh_region, LocationName.sh_sub1_tre1, baseID+71),
        LocationData(LocationName.sh_region, LocationName.sh_sub1_tre2, baseID+72),
        LocationData(LocationName.sh_region, LocationName.sh_sub2_tre1, baseID+73),
        LocationData(LocationName.sh_region, LocationName.sh_sub2_tre2, baseID+74),
        LocationData(LocationName.sh_region, LocationName.sh_sub3_tre1, baseID+75),
        LocationData(LocationName.sh_region, LocationName.sh_sub4_tre1, baseID+76),
        LocationData(LocationName.sh_region, LocationName.sh_sub4_tre2, baseID+77),
        LocationData(LocationName.sh_region, LocationName.sh_sub4_tre3, baseID+78),
        LocationData(LocationName.sh_region, LocationName.sh_sub5_tre1, baseID+79),
        LocationData(LocationName.sh_region, LocationName.sh_sub5_tre2, baseID+80),
        LocationData(LocationName.sh_region, LocationName.sh_sub6_tre1, baseID+81),
        LocationData(LocationName.sh_region, LocationName.sh_sub6_tre2, baseID+82),
        LocationData(LocationName.sh_region, LocationName.sh_sub6_tre3, baseID+83),
        LocationData(LocationName.sh_region, LocationName.sh_sub6_tre4, baseID+84),
        LocationData(LocationName.sh_region, LocationName.sh_sub7_tre1, baseID+85),
        # Perplexing Pool
        LocationData(LocationName.pp_region1, LocationName.pp_tre1, baseID+86, rule= lambda state: state.has(ItemName.onion_blue, player)),
        LocationData(LocationName.pp_region1, LocationName.pp_tre2, baseID+87, rule= lambda state: state.has(ItemName.onion_blue, player) and state.has(ItemName.onion_white, player)),
        LocationData(LocationName.pp_region1, LocationName.pp_tre3, baseID+88, rule= lambda state: state.has(ItemName.onion_yellow, player)),
        LocationData(LocationName.pp_region1, LocationName.pp_tre4, baseID+89, rule= lambda state: state.has(ItemName.onion_yellow, player)),
        LocationData(LocationName.pp_region5, LocationName.pp_tre5, baseID+90, rule= lambda state: state.has(ItemName.onion_blue, player)),
        LocationData(LocationName.pp_region6, LocationName.pp_tre6, baseID+91, rule= lambda state: state.has(ItemName.onion_blue, player) and state.has(ItemName.onion_white, player)),
        LocationData(LocationName.pp_region7, LocationName.pp_tre7, baseID+92, rule= lambda state: state.has(ItemName.onion_blue, player)),
        # Citadel of Spiders
        LocationData(LocationName.cos_region, LocationName.cos_sub1_tre1, baseID+93),
        LocationData(LocationName.cos_region, LocationName.cos_sub2_tre1, baseID+94),
        LocationData(LocationName.cos_region, LocationName.cos_sub2_tre2, baseID+95),
        LocationData(LocationName.cos_region, LocationName.cos_sub2_tre3, baseID+96),
        LocationData(LocationName.cos_region, LocationName.cos_sub3_tre1, baseID+97),
        LocationData(LocationName.cos_region, LocationName.cos_sub3_tre2, baseID+98),
        LocationData(LocationName.cos_region, LocationName.cos_sub4_tre1, baseID+99),
        LocationData(LocationName.cos_region, LocationName.cos_sub4_tre2, baseID+100),
        LocationData(LocationName.cos_region, LocationName.cos_sub4_tre3, baseID+101),
        LocationData(LocationName.cos_region, LocationName.cos_sub5_tre1, baseID+102),
        LocationData(LocationName.cos_region, LocationName.cos_sub5_tre2, baseID+103),
        # Gluttons Kitchen
        LocationData(LocationName.gk_region, LocationName.gk_sub1_tre1, baseID+104),
        LocationData(LocationName.gk_region, LocationName.gk_sub2_tre1, baseID+105),
        LocationData(LocationName.gk_region, LocationName.gk_sub2_tre2, baseID+106),
        LocationData(LocationName.gk_region, LocationName.gk_sub3_tre1, baseID+107),
        LocationData(LocationName.gk_region, LocationName.gk_sub3_tre2, baseID+108),
        LocationData(LocationName.gk_region, LocationName.gk_sub4_tre1, baseID+109),
        LocationData(LocationName.gk_region, LocationName.gk_sub4_tre2, baseID+110),
        LocationData(LocationName.gk_region, LocationName.gk_sub4_tre3, baseID+111),
        LocationData(LocationName.gk_region, LocationName.gk_sub5_tre1, baseID+112),
        LocationData(LocationName.gk_region, LocationName.gk_sub5_tre2, baseID+113),
        LocationData(LocationName.gk_region, LocationName.gk_sub6_tre1, baseID+114),
        LocationData(LocationName.gk_region, LocationName.gk_sub6_tre2, baseID+115),
        LocationData(LocationName.gk_region, LocationName.gk_sub6_tre3, baseID+116),
        LocationData(LocationName.gk_region, LocationName.gk_sub6_tre4, baseID+117),
        # Shower Room
        LocationData(LocationName.sr_region, LocationName.sr_sub1_tre1, baseID+118),
        LocationData(LocationName.sr_region, LocationName.sr_sub2_tre1, baseID+119),
        LocationData(LocationName.sr_region, LocationName.sr_sub2_tre2, baseID+120),
        LocationData(LocationName.sr_region, LocationName.sr_sub3_tre1, baseID+121),
        LocationData(LocationName.sr_region, LocationName.sr_sub3_tre2, baseID+122),
        LocationData(LocationName.sr_region, LocationName.sr_sub3_tre3, baseID+123),
        LocationData(LocationName.sr_region, LocationName.sr_sub4_tre1, baseID+124),
        LocationData(LocationName.sr_region, LocationName.sr_sub5_tre1, baseID+125),
        LocationData(LocationName.sr_region, LocationName.sr_sub5_tre2, baseID+126),
        LocationData(LocationName.sr_region, LocationName.sr_sub5_tre3, baseID+127),
        LocationData(LocationName.sr_region, LocationName.sr_sub6_tre1, baseID+128),
        LocationData(LocationName.sr_region, LocationName.sr_sub6_tre2, baseID+129),
        LocationData(LocationName.sr_region, LocationName.sr_sub6_tre3, baseID+130),
        LocationData(LocationName.sr_region, LocationName.sr_sub7_tre1, baseID+131),
        # WW
        LocationData(LocationName.ww_region1, LocationName.ww_tre1+145),
        LocationData(LocationName.ww_region2, LocationName.ww_tre1+146),
        LocationData(LocationName.ww_region3, LocationName.ww_tre1+147),
        LocationData(LocationName.ww_region4, LocationName.ww_tre1+148),
        LocationData(LocationName.ww_region4, LocationName.ww_tre1+149),
        # Cavern of Chaos
        LocationData(LocationName.coc_region, LocationName.coc_sub1_tre1, baseID+150),
        LocationData(LocationName.coc_region, LocationName.coc_sub1_tre2, baseID+151),
        LocationData(LocationName.coc_region, LocationName.coc_sub2_tre1, baseID+152),
        LocationData(LocationName.coc_region, LocationName.coc_sub2_tre2, baseID+153),
        LocationData(LocationName.coc_region, LocationName.coc_sub2_tre3, baseID+154),
        LocationData(LocationName.coc_region, LocationName.coc_sub3_tre1, baseID+155),
        LocationData(LocationName.coc_region, LocationName.coc_sub3_tre2, baseID+156),
        LocationData(LocationName.coc_region, LocationName.coc_sub4_tre1, baseID+157),
        LocationData(LocationName.coc_region, LocationName.coc_sub4_tre2, baseID+158),
        LocationData(LocationName.coc_region, LocationName.coc_sub6_tre1, baseID+159),
        LocationData(LocationName.coc_region, LocationName.coc_sub6_tre2, baseID+160),
        LocationData(LocationName.coc_region, LocationName.coc_sub7_tre1, baseID+161),
        LocationData(LocationName.coc_region, LocationName.coc_sub7_tre2, baseID+162),
        LocationData(LocationName.coc_region, LocationName.coc_sub8_tre1, baseID+163),
        LocationData(LocationName.coc_region, LocationName.coc_sub9_tre1, baseID+164),
        LocationData(LocationName.coc_region, LocationName.coc_sub9_tre2, baseID+165),
        LocationData(LocationName.coc_region, LocationName.coc_sub10_tre1, baseID+166),
        # Hole of Heros
        LocationData(LocationName.hoh_region, LocationName.hoh_sub1_tre1, baseID+167),
        LocationData(LocationName.hoh_region, LocationName.hoh_sub2_tre1, baseID+168),
        LocationData(LocationName.hoh_region, LocationName.hoh_sub3_tre1, baseID+169),
        LocationData(LocationName.hoh_region, LocationName.hoh_sub4_tre1, baseID+170),
        LocationData(LocationName.hoh_region, LocationName.hoh_sub6_tre1, baseID+171),
        LocationData(LocationName.hoh_region, LocationName.hoh_sub7_tre1, baseID+172),
        LocationData(LocationName.hoh_region, LocationName.hoh_sub9_tre1, baseID+173),
        LocationData(LocationName.hoh_region, LocationName.hoh_sub10_tre1, baseID+174),
        LocationData(LocationName.hoh_region, LocationName.hoh_sub11_tre1, baseID+175),
        LocationData(LocationName.hoh_region, LocationName.hoh_sub12_tre1, baseID+176),
        LocationData(LocationName.hoh_region, LocationName.hoh_sub13_tre1, baseID+177),
        LocationData(LocationName.hoh_region, LocationName.hoh_sub14_tre1, baseID+178),
        LocationData(LocationName.hoh_region, LocationName.hoh_sub15_tre1, baseID+179),
        # Dream Den
        LocationData(LocationName.dd_region, LocationName.dd_sub1_tre1, baseID+180),
        LocationData(LocationName.dd_region, LocationName.dd_sub2_tre1, baseID+181),
        LocationData(LocationName.dd_region, LocationName.dd_sub2_tre2, baseID+182),
        LocationData(LocationName.dd_region, LocationName.dd_sub3_tre1, baseID+183),
        LocationData(LocationName.dd_region, LocationName.dd_sub4_tre1, baseID+184),
        LocationData(LocationName.dd_region, LocationName.dd_sub5_tre1, baseID+185),
        LocationData(LocationName.dd_region, LocationName.dd_sub6_tre1, baseID+186),
        LocationData(LocationName.dd_region, LocationName.dd_sub7_tre1, baseID+187),
        LocationData(LocationName.dd_region, LocationName.dd_sub8_tre1, baseID+188),
        LocationData(LocationName.dd_region, LocationName.dd_sub8_tre1, baseID+189),
        LocationData(LocationName.dd_region, LocationName.dd_sub10_tre1, baseID+190),
        LocationData(LocationName.dd_region, LocationName.dd_sub11_tre1, baseID+191),
        LocationData(LocationName.dd_region, LocationName.dd_sub11_tre2, baseID+192),
        LocationData(LocationName.dd_region, LocationName.dd_sub12_tre1, baseID+193),
        LocationData(LocationName.dd_region, LocationName.dd_sub12_tre2, baseID+194),
        LocationData(LocationName.dd_region, LocationName.dd_sub13_tre1, baseID+195),
        LocationData(LocationName.dd_region, LocationName.dd_sub14_tre1, baseID+196),
        LocationData(LocationName.dd_region, LocationName.dd_sub14_tre2, baseID+197),
        LocationData(LocationName.dd_region, LocationName.dd_sub14_tre3, baseID+198),
        LocationData(LocationName.dd_region, LocationName.dd_sub14_tre4, baseID+199),
        LocationData(LocationName.dd_region, LocationName.dd_sub14_tre5, baseID+200),
        # Onions
        LocationData(LocationName.vor_region1, LocationName.vor_onion1, baseID+201),
        LocationData(LocationName.aw_region3, LocationName.aw_onion1, baseID+202),
        LocationData(LocationName.pp_region3, LocationName.pp_onion1, baseID+203),
    }
    return tuple(location_table)
